/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddFavorite201,
  AddFavoriteBody,
  DeleteFavorite200,
  GetFavorites200,
  GetFavoritesParams,
  UnauthorizedErrorResponse
} from '.././model';





/**
 * @summary 찜 목록 조회
 */
export const getFavorites = (
    params?: GetFavoritesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetFavorites200>> => {
    
    
    return axios.get(
      `/api/favorites`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetFavoritesQueryKey = (params?: GetFavoritesParams,) => {
    return [
    `/api/favorites`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetFavoritesQueryOptions = <TData = Awaited<ReturnType<typeof getFavorites>>, TError = AxiosError<UnauthorizedErrorResponse>>(params?: GetFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFavoritesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFavorites>>> = ({ signal }) => getFavorites(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFavoritesQueryResult = NonNullable<Awaited<ReturnType<typeof getFavorites>>>
export type GetFavoritesQueryError = AxiosError<UnauthorizedErrorResponse>


export function useGetFavorites<TData = Awaited<ReturnType<typeof getFavorites>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 params: undefined |  GetFavoritesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavorites>>,
          TError,
          Awaited<ReturnType<typeof getFavorites>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavorites<TData = Awaited<ReturnType<typeof getFavorites>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 params?: GetFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFavorites>>,
          TError,
          Awaited<ReturnType<typeof getFavorites>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFavorites<TData = Awaited<ReturnType<typeof getFavorites>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 params?: GetFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 찜 목록 조회
 */

export function useGetFavorites<TData = Awaited<ReturnType<typeof getFavorites>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 params?: GetFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFavorites>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFavoritesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 찜 추가
 */
export const addFavorite = (
    addFavoriteBody: AddFavoriteBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AddFavorite201>> => {
    
    
    return axios.post(
      `/api/favorites`,
      addFavoriteBody,options
    );
  }



export const getAddFavoriteMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addFavorite>>, TError,{data: AddFavoriteBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addFavorite>>, TError,{data: AddFavoriteBody}, TContext> => {

const mutationKey = ['addFavorite'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addFavorite>>, {data: AddFavoriteBody}> = (props) => {
          const {data} = props ?? {};

          return  addFavorite(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof addFavorite>>>
    export type AddFavoriteMutationBody = AddFavoriteBody
    export type AddFavoriteMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 찜 추가
 */
export const useAddFavorite = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addFavorite>>, TError,{data: AddFavoriteBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addFavorite>>,
        TError,
        {data: AddFavoriteBody},
        TContext
      > => {

      const mutationOptions = getAddFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 찜 삭제
 */
export const deleteFavorite = (
    favoriteId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteFavorite200>> => {
    
    
    return axios.delete(
      `/api/favorites/${favoriteId}`,options
    );
  }



export const getDeleteFavoriteMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFavorite>>, TError,{favoriteId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteFavorite>>, TError,{favoriteId: string}, TContext> => {

const mutationKey = ['deleteFavorite'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFavorite>>, {favoriteId: string}> = (props) => {
          const {favoriteId} = props ?? {};

          return  deleteFavorite(favoriteId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFavorite>>>
    
    export type DeleteFavoriteMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 찜 삭제
 */
export const useDeleteFavorite = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFavorite>>, TError,{favoriteId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFavorite>>,
        TError,
        {favoriteId: string},
        TContext
      > => {

      const mutationOptions = getDeleteFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    