/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CharacterCreateRequest,
  CreateCharacter201,
  DeleteCharacter200,
  GetProjectCharacters200,
  UnauthorizedErrorResponse,
  UpdateCharacter200
} from '.././model';





/**
 * @summary 캐릭터 목록 조회 (프로젝트별)
 */
export const getProjectCharacters = (
    projectId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetProjectCharacters200>> => {
    
    
    return axios.get(
      `/api/projects/${projectId}/characters`,options
    );
  }




export const getGetProjectCharactersQueryKey = (projectId?: string,) => {
    return [
    `/api/projects/${projectId}/characters`
    ] as const;
    }

    
export const getGetProjectCharactersQueryOptions = <TData = Awaited<ReturnType<typeof getProjectCharacters>>, TError = AxiosError<UnauthorizedErrorResponse>>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectCharactersQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectCharacters>>> = ({ signal }) => getProjectCharacters(projectId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectCharactersQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectCharacters>>>
export type GetProjectCharactersQueryError = AxiosError<UnauthorizedErrorResponse>


export function useGetProjectCharacters<TData = Awaited<ReturnType<typeof getProjectCharacters>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectCharacters>>,
          TError,
          Awaited<ReturnType<typeof getProjectCharacters>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectCharacters<TData = Awaited<ReturnType<typeof getProjectCharacters>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectCharacters>>,
          TError,
          Awaited<ReturnType<typeof getProjectCharacters>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectCharacters<TData = Awaited<ReturnType<typeof getProjectCharacters>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 캐릭터 목록 조회 (프로젝트별)
 */

export function useGetProjectCharacters<TData = Awaited<ReturnType<typeof getProjectCharacters>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectCharactersQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 캐릭터 생성
 */
export const createCharacter = (
    projectId: string,
    characterCreateRequest: CharacterCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateCharacter201>> => {
    
    
    return axios.post(
      `/api/projects/${projectId}/characters`,
      characterCreateRequest,options
    );
  }



export const getCreateCharacterMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCharacter>>, TError,{projectId: string;data: CharacterCreateRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createCharacter>>, TError,{projectId: string;data: CharacterCreateRequest}, TContext> => {

const mutationKey = ['createCharacter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCharacter>>, {projectId: string;data: CharacterCreateRequest}> = (props) => {
          const {projectId,data} = props ?? {};

          return  createCharacter(projectId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof createCharacter>>>
    export type CreateCharacterMutationBody = CharacterCreateRequest
    export type CreateCharacterMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 캐릭터 생성
 */
export const useCreateCharacter = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCharacter>>, TError,{projectId: string;data: CharacterCreateRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCharacter>>,
        TError,
        {projectId: string;data: CharacterCreateRequest},
        TContext
      > => {

      const mutationOptions = getCreateCharacterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 캐릭터 수정
 */
export const updateCharacter = (
    characterId: string,
    characterCreateRequest: CharacterCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateCharacter200>> => {
    
    
    return axios.put(
      `/api/characters/${characterId}`,
      characterCreateRequest,options
    );
  }



export const getUpdateCharacterMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCharacter>>, TError,{characterId: string;data: CharacterCreateRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateCharacter>>, TError,{characterId: string;data: CharacterCreateRequest}, TContext> => {

const mutationKey = ['updateCharacter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCharacter>>, {characterId: string;data: CharacterCreateRequest}> = (props) => {
          const {characterId,data} = props ?? {};

          return  updateCharacter(characterId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof updateCharacter>>>
    export type UpdateCharacterMutationBody = CharacterCreateRequest
    export type UpdateCharacterMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 캐릭터 수정
 */
export const useUpdateCharacter = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCharacter>>, TError,{characterId: string;data: CharacterCreateRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCharacter>>,
        TError,
        {characterId: string;data: CharacterCreateRequest},
        TContext
      > => {

      const mutationOptions = getUpdateCharacterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 캐릭터 삭제
 */
export const deleteCharacter = (
    characterId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteCharacter200>> => {
    
    
    return axios.delete(
      `/api/characters/${characterId}`,options
    );
  }



export const getDeleteCharacterMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCharacter>>, TError,{characterId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCharacter>>, TError,{characterId: string}, TContext> => {

const mutationKey = ['deleteCharacter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCharacter>>, {characterId: string}> = (props) => {
          const {characterId} = props ?? {};

          return  deleteCharacter(characterId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCharacter>>>
    
    export type DeleteCharacterMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 캐릭터 삭제
 */
export const useDeleteCharacter = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCharacter>>, TError,{characterId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCharacter>>,
        TError,
        {characterId: string},
        TContext
      > => {

      const mutationOptions = getDeleteCharacterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    