/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import type { CreateActorProfileBodyAgeGroup } from './createActorProfileBodyAgeGroup';

export type CreateActorProfileBody = {
  /** 활동명 */
  name: string;
  /** 한 줄 소개 */
  introduction: string;
  ageGroup: CreateActorProfileBodyAgeGroup;
  profileImage?: Blob;
  /** 특기 목록 */
  skills?: string[];
  /** 출생년도 */
  birthYear?: number;
  /** 키 (cm) */
  height?: number;
  /** 몸무게 (kg) */
  weight?: number;
};
