/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import type { GetActorsActorType } from './getActorsActorType';
import type { GetActorsGenderAge } from './getActorsGenderAge';
import type { GetActorsWorkType } from './getActorsWorkType';
import type { GetActorsSortBy } from './getActorsSortBy';

export type GetActorsParams = {
/**
 * 배우 유형
 */
actorType?: GetActorsActorType;
/**
 * 성별/나이대
 */
genderAge?: GetActorsGenderAge;
/**
 * 출연 작품 유형
 */
workType?: GetActorsWorkType;
/**
 * 정렬 기준
 */
sortBy?: GetActorsSortBy;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
