/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateShowreel201,
  CreateShowreelBody,
  DeleteShowreel200,
  GetActorShowreels200,
  ShowreelCreateRequest,
  UnauthorizedErrorResponse,
  UpdateShowreel200
} from '.././model';





/**
 * @summary 쇼릴 목록 조회
 */
export const getActorShowreels = (
    actorId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetActorShowreels200>> => {
    
    
    return axios.get(
      `/api/actors/${actorId}/showreels`,options
    );
  }




export const getGetActorShowreelsQueryKey = (actorId?: string,) => {
    return [
    `/api/actors/${actorId}/showreels`
    ] as const;
    }

    
export const getGetActorShowreelsQueryOptions = <TData = Awaited<ReturnType<typeof getActorShowreels>>, TError = AxiosError<unknown>>(actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActorShowreelsQueryKey(actorId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActorShowreels>>> = ({ signal }) => getActorShowreels(actorId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(actorId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActorShowreelsQueryResult = NonNullable<Awaited<ReturnType<typeof getActorShowreels>>>
export type GetActorShowreelsQueryError = AxiosError<unknown>


export function useGetActorShowreels<TData = Awaited<ReturnType<typeof getActorShowreels>>, TError = AxiosError<unknown>>(
 actorId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActorShowreels>>,
          TError,
          Awaited<ReturnType<typeof getActorShowreels>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActorShowreels<TData = Awaited<ReturnType<typeof getActorShowreels>>, TError = AxiosError<unknown>>(
 actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActorShowreels>>,
          TError,
          Awaited<ReturnType<typeof getActorShowreels>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActorShowreels<TData = Awaited<ReturnType<typeof getActorShowreels>>, TError = AxiosError<unknown>>(
 actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 쇼릴 목록 조회
 */

export function useGetActorShowreels<TData = Awaited<ReturnType<typeof getActorShowreels>>, TError = AxiosError<unknown>>(
 actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActorShowreelsQueryOptions(actorId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 쇼릴 생성
 */
export const createShowreel = (
    createShowreelBody: CreateShowreelBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateShowreel201>> => {
    
    const formData = new FormData();
if(createShowreelBody.videos !== undefined) {
 createShowreelBody.videos.forEach(value => formData.append(`videos`, value));
 }
formData.append(`roleType`, createShowreelBody.roleType)
formData.append(`workTitle`, createShowreelBody.workTitle)
if(createShowreelBody.year !== undefined) {
 formData.append(`year`, createShowreelBody.year.toString())
 }
if(createShowreelBody.genre !== undefined) {
 formData.append(`genre`, createShowreelBody.genre)
 }
if(createShowreelBody.role !== undefined) {
 formData.append(`role`, createShowreelBody.role)
 }
if(createShowreelBody.representativeGenre !== undefined) {
 formData.append(`representativeGenre`, createShowreelBody.representativeGenre)
 }
if(createShowreelBody.tags !== undefined) {
 createShowreelBody.tags.forEach(value => formData.append(`tags`, value));
 }

    return axios.post(
      `/api/showreels`,
      formData,options
    );
  }



export const getCreateShowreelMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShowreel>>, TError,{data: CreateShowreelBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createShowreel>>, TError,{data: CreateShowreelBody}, TContext> => {

const mutationKey = ['createShowreel'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createShowreel>>, {data: CreateShowreelBody}> = (props) => {
          const {data} = props ?? {};

          return  createShowreel(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateShowreelMutationResult = NonNullable<Awaited<ReturnType<typeof createShowreel>>>
    export type CreateShowreelMutationBody = CreateShowreelBody
    export type CreateShowreelMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 쇼릴 생성
 */
export const useCreateShowreel = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShowreel>>, TError,{data: CreateShowreelBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createShowreel>>,
        TError,
        {data: CreateShowreelBody},
        TContext
      > => {

      const mutationOptions = getCreateShowreelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 쇼릴 수정
 */
export const updateShowreel = (
    showreelId: string,
    showreelCreateRequest: ShowreelCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateShowreel200>> => {
    
    
    return axios.put(
      `/api/showreels/${showreelId}`,
      showreelCreateRequest,options
    );
  }



export const getUpdateShowreelMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShowreel>>, TError,{showreelId: string;data: ShowreelCreateRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateShowreel>>, TError,{showreelId: string;data: ShowreelCreateRequest}, TContext> => {

const mutationKey = ['updateShowreel'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateShowreel>>, {showreelId: string;data: ShowreelCreateRequest}> = (props) => {
          const {showreelId,data} = props ?? {};

          return  updateShowreel(showreelId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateShowreelMutationResult = NonNullable<Awaited<ReturnType<typeof updateShowreel>>>
    export type UpdateShowreelMutationBody = ShowreelCreateRequest
    export type UpdateShowreelMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 쇼릴 수정
 */
export const useUpdateShowreel = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateShowreel>>, TError,{showreelId: string;data: ShowreelCreateRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateShowreel>>,
        TError,
        {showreelId: string;data: ShowreelCreateRequest},
        TContext
      > => {

      const mutationOptions = getUpdateShowreelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 쇼릴 삭제
 */
export const deleteShowreel = (
    showreelId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteShowreel200>> => {
    
    
    return axios.delete(
      `/api/showreels/${showreelId}`,options
    );
  }



export const getDeleteShowreelMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShowreel>>, TError,{showreelId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteShowreel>>, TError,{showreelId: string}, TContext> => {

const mutationKey = ['deleteShowreel'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteShowreel>>, {showreelId: string}> = (props) => {
          const {showreelId} = props ?? {};

          return  deleteShowreel(showreelId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteShowreelMutationResult = NonNullable<Awaited<ReturnType<typeof deleteShowreel>>>
    
    export type DeleteShowreelMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 쇼릴 삭제
 */
export const useDeleteShowreel = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteShowreel>>, TError,{showreelId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteShowreel>>,
        TError,
        {showreelId: string},
        TContext
      > => {

      const mutationOptions = getDeleteShowreelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    