/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetMyProfile200,
  GetNotificationSettings200,
  NotificationSettings,
  UnauthorizedErrorResponse,
  UpdateMyProfile200,
  UpdateMyProfileBody,
  UpdateNotificationSettings200
} from '.././model';





/**
 * @summary 내 정보 조회
 */
export const getMyProfile = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetMyProfile200>> => {
    
    
    return axios.get(
      `/api/users/me`,options
    );
  }




export const getGetMyProfileQueryKey = () => {
    return [
    `/api/users/me`
    ] as const;
    }

    
export const getGetMyProfileQueryOptions = <TData = Awaited<ReturnType<typeof getMyProfile>>, TError = AxiosError<UnauthorizedErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyProfile>>> = ({ signal }) => getMyProfile({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getMyProfile>>>
export type GetMyProfileQueryError = AxiosError<UnauthorizedErrorResponse>


export function useGetMyProfile<TData = Awaited<ReturnType<typeof getMyProfile>>, TError = AxiosError<UnauthorizedErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyProfile>>,
          TError,
          Awaited<ReturnType<typeof getMyProfile>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyProfile<TData = Awaited<ReturnType<typeof getMyProfile>>, TError = AxiosError<UnauthorizedErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyProfile>>,
          TError,
          Awaited<ReturnType<typeof getMyProfile>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyProfile<TData = Awaited<ReturnType<typeof getMyProfile>>, TError = AxiosError<UnauthorizedErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 정보 조회
 */

export function useGetMyProfile<TData = Awaited<ReturnType<typeof getMyProfile>>, TError = AxiosError<UnauthorizedErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 프로필 수정
 */
export const updateMyProfile = (
    updateMyProfileBody: UpdateMyProfileBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateMyProfile200>> => {
    
    const formData = new FormData();
if(updateMyProfileBody.name !== undefined) {
 formData.append(`name`, updateMyProfileBody.name)
 }
if(updateMyProfileBody.position !== undefined) {
 formData.append(`position`, updateMyProfileBody.position)
 }
if(updateMyProfileBody.agency !== undefined) {
 formData.append(`agency`, updateMyProfileBody.agency)
 }
if(updateMyProfileBody.phone !== undefined) {
 formData.append(`phone`, updateMyProfileBody.phone)
 }
if(updateMyProfileBody.bio !== undefined) {
 formData.append(`bio`, updateMyProfileBody.bio)
 }
if(updateMyProfileBody.fee !== undefined) {
 formData.append(`fee`, updateMyProfileBody.fee)
 }
if(updateMyProfileBody.height !== undefined) {
 formData.append(`height`, updateMyProfileBody.height.toString())
 }
if(updateMyProfileBody.weight !== undefined) {
 formData.append(`weight`, updateMyProfileBody.weight.toString())
 }
if(updateMyProfileBody.profileImage !== undefined) {
 formData.append(`profileImage`, updateMyProfileBody.profileImage)
 }

    return axios.put(
      `/api/users/profile`,
      formData,options
    );
  }



export const getUpdateMyProfileMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyProfile>>, TError,{data: UpdateMyProfileBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateMyProfile>>, TError,{data: UpdateMyProfileBody}, TContext> => {

const mutationKey = ['updateMyProfile'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMyProfile>>, {data: UpdateMyProfileBody}> = (props) => {
          const {data} = props ?? {};

          return  updateMyProfile(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMyProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateMyProfile>>>
    export type UpdateMyProfileMutationBody = UpdateMyProfileBody
    export type UpdateMyProfileMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 프로필 수정
 */
export const useUpdateMyProfile = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMyProfile>>, TError,{data: UpdateMyProfileBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMyProfile>>,
        TError,
        {data: UpdateMyProfileBody},
        TContext
      > => {

      const mutationOptions = getUpdateMyProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 알림 설정 조회
 */
export const getNotificationSettings = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetNotificationSettings200>> => {
    
    
    return axios.get(
      `/api/users/settings/notifications`,options
    );
  }




export const getGetNotificationSettingsQueryKey = () => {
    return [
    `/api/users/settings/notifications`
    ] as const;
    }

    
export const getGetNotificationSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getNotificationSettings>>, TError = AxiosError<UnauthorizedErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationSettings>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotificationSettingsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationSettings>>> = ({ signal }) => getNotificationSettings({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotificationSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNotificationSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getNotificationSettings>>>
export type GetNotificationSettingsQueryError = AxiosError<UnauthorizedErrorResponse>


export function useGetNotificationSettings<TData = Awaited<ReturnType<typeof getNotificationSettings>>, TError = AxiosError<UnauthorizedErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationSettings>>,
          TError,
          Awaited<ReturnType<typeof getNotificationSettings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotificationSettings<TData = Awaited<ReturnType<typeof getNotificationSettings>>, TError = AxiosError<UnauthorizedErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationSettings>>,
          TError,
          Awaited<ReturnType<typeof getNotificationSettings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotificationSettings<TData = Awaited<ReturnType<typeof getNotificationSettings>>, TError = AxiosError<UnauthorizedErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationSettings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 알림 설정 조회
 */

export function useGetNotificationSettings<TData = Awaited<ReturnType<typeof getNotificationSettings>>, TError = AxiosError<UnauthorizedErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotificationSettings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNotificationSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 알림 설정 수정
 */
export const updateNotificationSettings = (
    notificationSettings: NotificationSettings, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateNotificationSettings200>> => {
    
    
    return axios.put(
      `/api/users/settings/notifications`,
      notificationSettings,options
    );
  }



export const getUpdateNotificationSettingsMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotificationSettings>>, TError,{data: NotificationSettings}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateNotificationSettings>>, TError,{data: NotificationSettings}, TContext> => {

const mutationKey = ['updateNotificationSettings'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNotificationSettings>>, {data: NotificationSettings}> = (props) => {
          const {data} = props ?? {};

          return  updateNotificationSettings(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateNotificationSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updateNotificationSettings>>>
    export type UpdateNotificationSettingsMutationBody = NotificationSettings
    export type UpdateNotificationSettingsMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 알림 설정 수정
 */
export const useUpdateNotificationSettings = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotificationSettings>>, TError,{data: NotificationSettings}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateNotificationSettings>>,
        TError,
        {data: NotificationSettings},
        TContext
      > => {

      const mutationOptions = getUpdateNotificationSettingsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    