/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorResponse,
  UnauthorizedErrorResponse,
  UploadImage200,
  UploadImageBody,
  UploadVideo200,
  UploadVideoBody
} from '.././model';





/**
 * @summary 이미지 업로드
 */
export const uploadImage = (
    uploadImageBody: UploadImageBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UploadImage200>> => {
    
    const formData = new FormData();
formData.append(`file`, uploadImageBody.file)
formData.append(`type`, uploadImageBody.type)

    return axios.post(
      `/api/upload/image`,
      formData,options
    );
  }



export const getUploadImageMutationOptions = <TError = AxiosError<ErrorResponse | UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadImage>>, TError,{data: UploadImageBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof uploadImage>>, TError,{data: UploadImageBody}, TContext> => {

const mutationKey = ['uploadImage'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadImage>>, {data: UploadImageBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadImage(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadImageMutationResult = NonNullable<Awaited<ReturnType<typeof uploadImage>>>
    export type UploadImageMutationBody = UploadImageBody
    export type UploadImageMutationError = AxiosError<ErrorResponse | UnauthorizedErrorResponse>

    /**
 * @summary 이미지 업로드
 */
export const useUploadImage = <TError = AxiosError<ErrorResponse | UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadImage>>, TError,{data: UploadImageBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadImage>>,
        TError,
        {data: UploadImageBody},
        TContext
      > => {

      const mutationOptions = getUploadImageMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 영상 업로드
 */
export const uploadVideo = (
    uploadVideoBody: UploadVideoBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UploadVideo200>> => {
    
    const formData = new FormData();
formData.append(`file`, uploadVideoBody.file)
formData.append(`type`, uploadVideoBody.type)

    return axios.post(
      `/api/upload/video`,
      formData,options
    );
  }



export const getUploadVideoMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadVideo>>, TError,{data: UploadVideoBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof uploadVideo>>, TError,{data: UploadVideoBody}, TContext> => {

const mutationKey = ['uploadVideo'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadVideo>>, {data: UploadVideoBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadVideo(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadVideoMutationResult = NonNullable<Awaited<ReturnType<typeof uploadVideo>>>
    export type UploadVideoMutationBody = UploadVideoBody
    export type UploadVideoMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 영상 업로드
 */
export const useUploadVideo = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadVideo>>, TError,{data: UploadVideoBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadVideo>>,
        TError,
        {data: UploadVideoBody},
        TContext
      > => {

      const mutationOptions = getUploadVideoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    