/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ContactActor200,
  ContactActorBody,
  CreateActorProfile201,
  CreateActorProfileBody,
  GetActorDetail200,
  GetActors200,
  GetActorsParams,
  NotFoundErrorResponse,
  RecommendActors200,
  RecommendActorsBody,
  UnauthorizedErrorResponse
} from '.././model';





/**
 * 필터/정렬 조건으로 배우 목록 검색
 * @summary 배우 목록 조회
 */
export const getActors = (
    params?: GetActorsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetActors200>> => {
    
    
    return axios.get(
      `/api/actors`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetActorsQueryKey = (params?: GetActorsParams,) => {
    return [
    `/api/actors`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetActorsQueryOptions = <TData = Awaited<ReturnType<typeof getActors>>, TError = AxiosError<unknown>>(params?: GetActorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActors>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActorsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActors>>> = ({ signal }) => getActors(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActorsQueryResult = NonNullable<Awaited<ReturnType<typeof getActors>>>
export type GetActorsQueryError = AxiosError<unknown>


export function useGetActors<TData = Awaited<ReturnType<typeof getActors>>, TError = AxiosError<unknown>>(
 params: undefined |  GetActorsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActors>>,
          TError,
          Awaited<ReturnType<typeof getActors>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActors<TData = Awaited<ReturnType<typeof getActors>>, TError = AxiosError<unknown>>(
 params?: GetActorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActors>>,
          TError,
          Awaited<ReturnType<typeof getActors>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActors<TData = Awaited<ReturnType<typeof getActors>>, TError = AxiosError<unknown>>(
 params?: GetActorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActors>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 배우 목록 조회
 */

export function useGetActors<TData = Awaited<ReturnType<typeof getActors>>, TError = AxiosError<unknown>>(
 params?: GetActorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActors>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActorsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * 배우 프로필, 필모그래피, 쇼릴 등 상세 정보 조회
 * @summary 배우 상세 조회
 */
export const getActorDetail = (
    actorId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetActorDetail200>> => {
    
    
    return axios.get(
      `/api/actors/${actorId}`,options
    );
  }




export const getGetActorDetailQueryKey = (actorId?: string,) => {
    return [
    `/api/actors/${actorId}`
    ] as const;
    }

    
export const getGetActorDetailQueryOptions = <TData = Awaited<ReturnType<typeof getActorDetail>>, TError = AxiosError<NotFoundErrorResponse>>(actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorDetail>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetActorDetailQueryKey(actorId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getActorDetail>>> = ({ signal }) => getActorDetail(actorId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(actorId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getActorDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetActorDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getActorDetail>>>
export type GetActorDetailQueryError = AxiosError<NotFoundErrorResponse>


export function useGetActorDetail<TData = Awaited<ReturnType<typeof getActorDetail>>, TError = AxiosError<NotFoundErrorResponse>>(
 actorId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActorDetail>>,
          TError,
          Awaited<ReturnType<typeof getActorDetail>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActorDetail<TData = Awaited<ReturnType<typeof getActorDetail>>, TError = AxiosError<NotFoundErrorResponse>>(
 actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActorDetail>>,
          TError,
          Awaited<ReturnType<typeof getActorDetail>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetActorDetail<TData = Awaited<ReturnType<typeof getActorDetail>>, TError = AxiosError<NotFoundErrorResponse>>(
 actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorDetail>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 배우 상세 조회
 */

export function useGetActorDetail<TData = Awaited<ReturnType<typeof getActorDetail>>, TError = AxiosError<NotFoundErrorResponse>>(
 actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorDetail>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetActorDetailQueryOptions(actorId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * 프로젝트/캐릭터 정보 기반 AI 배우 추천
 * @summary AI 배우 추천
 */
export const recommendActors = (
    recommendActorsBody: RecommendActorsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RecommendActors200>> => {
    
    
    return axios.post(
      `/api/actors/recommend`,
      recommendActorsBody,options
    );
  }



export const getRecommendActorsMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recommendActors>>, TError,{data: RecommendActorsBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof recommendActors>>, TError,{data: RecommendActorsBody}, TContext> => {

const mutationKey = ['recommendActors'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recommendActors>>, {data: RecommendActorsBody}> = (props) => {
          const {data} = props ?? {};

          return  recommendActors(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RecommendActorsMutationResult = NonNullable<Awaited<ReturnType<typeof recommendActors>>>
    export type RecommendActorsMutationBody = RecommendActorsBody
    export type RecommendActorsMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary AI 배우 추천
 */
export const useRecommendActors = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recommendActors>>, TError,{data: RecommendActorsBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof recommendActors>>,
        TError,
        {data: RecommendActorsBody},
        TContext
      > => {

      const mutationOptions = getRecommendActorsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 배우 회원가입 시 프로필 등록
 * @summary 배우 프로필 등록
 */
export const createActorProfile = (
    createActorProfileBody: CreateActorProfileBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateActorProfile201>> => {
    
    const formData = new FormData();
formData.append(`name`, createActorProfileBody.name)
formData.append(`introduction`, createActorProfileBody.introduction)
formData.append(`ageGroup`, createActorProfileBody.ageGroup)
if(createActorProfileBody.profileImage !== undefined) {
 formData.append(`profileImage`, createActorProfileBody.profileImage)
 }

    return axios.post(
      `/api/actors/profile`,
      formData,options
    );
  }



export const getCreateActorProfileMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createActorProfile>>, TError,{data: CreateActorProfileBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createActorProfile>>, TError,{data: CreateActorProfileBody}, TContext> => {

const mutationKey = ['createActorProfile'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createActorProfile>>, {data: CreateActorProfileBody}> = (props) => {
          const {data} = props ?? {};

          return  createActorProfile(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateActorProfileMutationResult = NonNullable<Awaited<ReturnType<typeof createActorProfile>>>
    export type CreateActorProfileMutationBody = CreateActorProfileBody
    export type CreateActorProfileMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 배우 프로필 등록
 */
export const useCreateActorProfile = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createActorProfile>>, TError,{data: CreateActorProfileBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createActorProfile>>,
        TError,
        {data: CreateActorProfileBody},
        TContext
      > => {

      const mutationOptions = getCreateActorProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 배우 포트폴리오 PDF 다운로드
 * @summary 포트폴리오 다운로드
 */
export const downloadActorPortfolio = (
    actorId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    
    
    return axios.get(
      `/api/actors/${actorId}/portfolio`,{
        responseType: 'blob',
    ...options,}
    );
  }




export const getDownloadActorPortfolioQueryKey = (actorId?: string,) => {
    return [
    `/api/actors/${actorId}/portfolio`
    ] as const;
    }

    
export const getDownloadActorPortfolioQueryOptions = <TData = Awaited<ReturnType<typeof downloadActorPortfolio>>, TError = AxiosError<NotFoundErrorResponse>>(actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadActorPortfolio>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadActorPortfolioQueryKey(actorId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadActorPortfolio>>> = ({ signal }) => downloadActorPortfolio(actorId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(actorId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadActorPortfolio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadActorPortfolioQueryResult = NonNullable<Awaited<ReturnType<typeof downloadActorPortfolio>>>
export type DownloadActorPortfolioQueryError = AxiosError<NotFoundErrorResponse>


export function useDownloadActorPortfolio<TData = Awaited<ReturnType<typeof downloadActorPortfolio>>, TError = AxiosError<NotFoundErrorResponse>>(
 actorId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadActorPortfolio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadActorPortfolio>>,
          TError,
          Awaited<ReturnType<typeof downloadActorPortfolio>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadActorPortfolio<TData = Awaited<ReturnType<typeof downloadActorPortfolio>>, TError = AxiosError<NotFoundErrorResponse>>(
 actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadActorPortfolio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadActorPortfolio>>,
          TError,
          Awaited<ReturnType<typeof downloadActorPortfolio>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadActorPortfolio<TData = Awaited<ReturnType<typeof downloadActorPortfolio>>, TError = AxiosError<NotFoundErrorResponse>>(
 actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadActorPortfolio>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 포트폴리오 다운로드
 */

export function useDownloadActorPortfolio<TData = Awaited<ReturnType<typeof downloadActorPortfolio>>, TError = AxiosError<NotFoundErrorResponse>>(
 actorId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadActorPortfolio>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadActorPortfolioQueryOptions(actorId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * 에이전시가 배우에게 캐스팅 제안 전송
 * @summary 배우에게 연락하기
 */
export const contactActor = (
    actorId: string,
    contactActorBody: ContactActorBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ContactActor200>> => {
    
    
    return axios.post(
      `/api/actors/${actorId}/contact`,
      contactActorBody,options
    );
  }



export const getContactActorMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactActor>>, TError,{actorId: string;data: ContactActorBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof contactActor>>, TError,{actorId: string;data: ContactActorBody}, TContext> => {

const mutationKey = ['contactActor'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof contactActor>>, {actorId: string;data: ContactActorBody}> = (props) => {
          const {actorId,data} = props ?? {};

          return  contactActor(actorId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ContactActorMutationResult = NonNullable<Awaited<ReturnType<typeof contactActor>>>
    export type ContactActorMutationBody = ContactActorBody
    export type ContactActorMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 배우에게 연락하기
 */
export const useContactActor = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof contactActor>>, TError,{actorId: string;data: ContactActorBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof contactActor>>,
        TError,
        {actorId: string;data: ContactActorBody},
        TContext
      > => {

      const mutationOptions = getContactActorMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    