/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateNotice200,
  CreateNoticeRequest,
  DeleteNotice200,
  ForbiddenErrorResponse,
  NotFoundErrorResponse,
  UnauthorizedErrorResponse,
  UpdateNotice200,
  UpdateNoticeRequest
} from '.././model';

import { customFetch } from '../../lib/fetcher';
import type { ErrorType , BodyType } from '../../lib/fetcher';




/**
 * 새 공지사항을 등록합니다 (관리자 전용)
 * @summary 공지사항 등록
 */
export const createNotice = (
    createNoticeRequest: BodyType<CreateNoticeRequest>,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreateNotice200>(
      {url: `/api/admin/notices`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNoticeRequest, signal
    },
      );
    }
  


export const getCreateNoticeMutationOptions = <TError = ErrorType<UnauthorizedErrorResponse | ForbiddenErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNotice>>, TError,{data: BodyType<CreateNoticeRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createNotice>>, TError,{data: BodyType<CreateNoticeRequest>}, TContext> => {

const mutationKey = ['createNotice'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNotice>>, {data: BodyType<CreateNoticeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createNotice(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateNoticeMutationResult = NonNullable<Awaited<ReturnType<typeof createNotice>>>
    export type CreateNoticeMutationBody = BodyType<CreateNoticeRequest>
    export type CreateNoticeMutationError = ErrorType<UnauthorizedErrorResponse | ForbiddenErrorResponse>

    /**
 * @summary 공지사항 등록
 */
export const useCreateNotice = <TError = ErrorType<UnauthorizedErrorResponse | ForbiddenErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNotice>>, TError,{data: BodyType<CreateNoticeRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createNotice>>,
        TError,
        {data: BodyType<CreateNoticeRequest>},
        TContext
      > => {

      const mutationOptions = getCreateNoticeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 공지사항을 수정합니다 (관리자 전용)
 * @summary 공지사항 수정
 */
export const updateNotice = (
    noticeId: string,
    updateNoticeRequest: BodyType<UpdateNoticeRequest>,
 ) => {
      
      
      return customFetch<UpdateNotice200>(
      {url: `/api/admin/notices/${noticeId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateNoticeRequest
    },
      );
    }
  


export const getUpdateNoticeMutationOptions = <TError = ErrorType<UnauthorizedErrorResponse | ForbiddenErrorResponse | NotFoundErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotice>>, TError,{noticeId: string;data: BodyType<UpdateNoticeRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateNotice>>, TError,{noticeId: string;data: BodyType<UpdateNoticeRequest>}, TContext> => {

const mutationKey = ['updateNotice'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNotice>>, {noticeId: string;data: BodyType<UpdateNoticeRequest>}> = (props) => {
          const {noticeId,data} = props ?? {};

          return  updateNotice(noticeId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateNoticeMutationResult = NonNullable<Awaited<ReturnType<typeof updateNotice>>>
    export type UpdateNoticeMutationBody = BodyType<UpdateNoticeRequest>
    export type UpdateNoticeMutationError = ErrorType<UnauthorizedErrorResponse | ForbiddenErrorResponse | NotFoundErrorResponse>

    /**
 * @summary 공지사항 수정
 */
export const useUpdateNotice = <TError = ErrorType<UnauthorizedErrorResponse | ForbiddenErrorResponse | NotFoundErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNotice>>, TError,{noticeId: string;data: BodyType<UpdateNoticeRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateNotice>>,
        TError,
        {noticeId: string;data: BodyType<UpdateNoticeRequest>},
        TContext
      > => {

      const mutationOptions = getUpdateNoticeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 공지사항을 삭제합니다 (관리자 전용)
 * @summary 공지사항 삭제
 */
export const deleteNotice = (
    noticeId: string,
 ) => {
      
      
      return customFetch<DeleteNotice200>(
      {url: `/api/admin/notices/${noticeId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteNoticeMutationOptions = <TError = ErrorType<UnauthorizedErrorResponse | ForbiddenErrorResponse | NotFoundErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotice>>, TError,{noticeId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteNotice>>, TError,{noticeId: string}, TContext> => {

const mutationKey = ['deleteNotice'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNotice>>, {noticeId: string}> = (props) => {
          const {noticeId} = props ?? {};

          return  deleteNotice(noticeId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteNoticeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNotice>>>
    
    export type DeleteNoticeMutationError = ErrorType<UnauthorizedErrorResponse | ForbiddenErrorResponse | NotFoundErrorResponse>

    /**
 * @summary 공지사항 삭제
 */
export const useDeleteNotice = <TError = ErrorType<UnauthorizedErrorResponse | ForbiddenErrorResponse | NotFoundErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotice>>, TError,{noticeId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNotice>>,
        TError,
        {noticeId: string},
        TContext
      > => {

      const mutationOptions = getDeleteNoticeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    