/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateNotice200,
  DeleteNotice200,
  UpdateNotice200
} from '.././model';


export const getCreateNoticeResponseMock = (overrideResponse: Partial< CreateNotice200 > = {}): CreateNotice200 => ({success: true, data: {id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, ...overrideResponse})

export const getUpdateNoticeResponseMock = (overrideResponse: Partial< UpdateNotice200 > = {}): UpdateNotice200 => ({success: true, data: {id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, ...overrideResponse})

export const getDeleteNoticeResponseMock = (overrideResponse: Partial< DeleteNotice200 > = {}): DeleteNotice200 => ({success: true, data: {message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, ...overrideResponse})


export const getCreateNoticeMockHandler = (overrideResponse?: CreateNotice200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateNotice200> | CreateNotice200), options?: RequestHandlerOptions) => {
  return http.post('*/api/admin/notices', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateNoticeResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateNoticeMockHandler = (overrideResponse?: UpdateNotice200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateNotice200> | UpdateNotice200), options?: RequestHandlerOptions) => {
  return http.put('*/api/admin/notices/:noticeId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateNoticeResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteNoticeMockHandler = (overrideResponse?: DeleteNotice200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteNotice200> | DeleteNotice200), options?: RequestHandlerOptions) => {
  return http.delete('*/api/admin/notices/:noticeId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteNoticeResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAdminMock = () => [
  getCreateNoticeMockHandler(),
  getUpdateNoticeMockHandler(),
  getDeleteNoticeMockHandler()
]
