/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateProject201,
  DeleteProject200,
  GetProjectDetail200,
  GetProjects200,
  GetProjectsParams,
  NotFoundErrorResponse,
  ProjectCreateRequest,
  UnauthorizedErrorResponse,
  UpdateProject200
} from '.././model';





/**
 * @summary 프로젝트 목록 조회
 */
export const getProjects = (
    params?: GetProjectsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetProjects200>> => {
    
    
    return axios.get(
      `/api/projects`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetProjectsQueryKey = (params?: GetProjectsParams,) => {
    return [
    `/api/projects`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getProjects>>, TError = AxiosError<UnauthorizedErrorResponse>>(params?: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjects>>> = ({ signal }) => getProjects(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getProjects>>>
export type GetProjectsQueryError = AxiosError<UnauthorizedErrorResponse>


export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 params: undefined |  GetProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 params?: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 params?: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 프로젝트 목록 조회
 */

export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = AxiosError<UnauthorizedErrorResponse>>(
 params?: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 프로젝트 생성
 */
export const createProject = (
    projectCreateRequest: ProjectCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateProject201>> => {
    
    
    return axios.post(
      `/api/projects`,
      projectCreateRequest,options
    );
  }



export const getCreateProjectMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: ProjectCreateRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: ProjectCreateRequest}, TContext> => {

const mutationKey = ['createProject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProject>>, {data: ProjectCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProject(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>
    export type CreateProjectMutationBody = ProjectCreateRequest
    export type CreateProjectMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 프로젝트 생성
 */
export const useCreateProject = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: ProjectCreateRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProject>>,
        TError,
        {data: ProjectCreateRequest},
        TContext
      > => {

      const mutationOptions = getCreateProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 프로젝트 상세 조회
 */
export const getProjectDetail = (
    projectId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetProjectDetail200>> => {
    
    
    return axios.get(
      `/api/projects/${projectId}`,options
    );
  }




export const getGetProjectDetailQueryKey = (projectId?: string,) => {
    return [
    `/api/projects/${projectId}`
    ] as const;
    }

    
export const getGetProjectDetailQueryOptions = <TData = Awaited<ReturnType<typeof getProjectDetail>>, TError = AxiosError<UnauthorizedErrorResponse | NotFoundErrorResponse>>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectDetailQueryKey(projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectDetail>>> = ({ signal }) => getProjectDetail(projectId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectDetail>>>
export type GetProjectDetailQueryError = AxiosError<UnauthorizedErrorResponse | NotFoundErrorResponse>


export function useGetProjectDetail<TData = Awaited<ReturnType<typeof getProjectDetail>>, TError = AxiosError<UnauthorizedErrorResponse | NotFoundErrorResponse>>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectDetail>>,
          TError,
          Awaited<ReturnType<typeof getProjectDetail>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectDetail<TData = Awaited<ReturnType<typeof getProjectDetail>>, TError = AxiosError<UnauthorizedErrorResponse | NotFoundErrorResponse>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectDetail>>,
          TError,
          Awaited<ReturnType<typeof getProjectDetail>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectDetail<TData = Awaited<ReturnType<typeof getProjectDetail>>, TError = AxiosError<UnauthorizedErrorResponse | NotFoundErrorResponse>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 프로젝트 상세 조회
 */

export function useGetProjectDetail<TData = Awaited<ReturnType<typeof getProjectDetail>>, TError = AxiosError<UnauthorizedErrorResponse | NotFoundErrorResponse>>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectDetailQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 프로젝트 수정
 */
export const updateProject = (
    projectId: string,
    projectCreateRequest: ProjectCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateProject200>> => {
    
    
    return axios.put(
      `/api/projects/${projectId}`,
      projectCreateRequest,options
    );
  }



export const getUpdateProjectMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse | NotFoundErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: string;data: ProjectCreateRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: string;data: ProjectCreateRequest}, TContext> => {

const mutationKey = ['updateProject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProject>>, {projectId: string;data: ProjectCreateRequest}> = (props) => {
          const {projectId,data} = props ?? {};

          return  updateProject(projectId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof updateProject>>>
    export type UpdateProjectMutationBody = ProjectCreateRequest
    export type UpdateProjectMutationError = AxiosError<UnauthorizedErrorResponse | NotFoundErrorResponse>

    /**
 * @summary 프로젝트 수정
 */
export const useUpdateProject = <TError = AxiosError<UnauthorizedErrorResponse | NotFoundErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: string;data: ProjectCreateRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProject>>,
        TError,
        {projectId: string;data: ProjectCreateRequest},
        TContext
      > => {

      const mutationOptions = getUpdateProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 프로젝트 삭제
 */
export const deleteProject = (
    projectId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteProject200>> => {
    
    
    return axios.delete(
      `/api/projects/${projectId}`,options
    );
  }



export const getDeleteProjectMutationOptions = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: string}, TContext> => {

const mutationKey = ['deleteProject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProject>>, {projectId: string}> = (props) => {
          const {projectId} = props ?? {};

          return  deleteProject(projectId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>
    
    export type DeleteProjectMutationError = AxiosError<UnauthorizedErrorResponse>

    /**
 * @summary 프로젝트 삭제
 */
export const useDeleteProject = <TError = AxiosError<UnauthorizedErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProject>>,
        TError,
        {projectId: string},
        TContext
      > => {

      const mutationOptions = getDeleteProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    